#:import dp kivy.metrics.dp
#:import Window kivy.core.window.Window

<ImageChip>:
    size_hint_x: None      
    size_hint_y: None
    padding: dp(10), dp(6)
    spacing: dp(6)
    height: self.minimum_height
    width: self.minimum_width

    canvas.before:
        Color:
            rgba: 120/255, 200/255, 214/255, 1
        RoundedRectangle:
            pos: self.x, self.y
            size: self.width, self.height
            radius: [dp(16), dp(16), dp(16), dp(16)]

    Label:
        text: root.text
        size_hint_x: None
        text_size: None, None
        halign: "left"
        valign: "middle"
        size: self.texture_size
        color: 0, 0, 0, 1

<ChatBubble>:
    size_hint_x: None 
    padding: dp(8)
    spacing: dp(4)
    canvas.before:
        Color:
            rgba: (0.47, 0.78, 0.84, 1) if root.is_user else (109/255,186/255,99/255,1)
        RoundedRectangle:
            pos: self.x, self.y
            size: self.width, self.height
            radius: [dp(12), dp(3), dp(12), dp(12)] if root.is_user else [dp(3), dp(12), dp(12), dp(12)]

    Label:
        id: msg_label
        text: root.text
        text_size: (self.width - dp(6), None) 
        size_hint_y: None
        height: self.texture_size[1]
        halign: "left"
        valign: "middle"
        color: 0, 0, 0, 1
        shorten: False


<TextBar@Widget>:
    height: dp(56)
    padding: dp(10), dp(8)
    spacing: dp(8)

    canvas.before:
        Color: 
            rgba: 3/255, 26/255, 0/255, 1
        RoundedRectangle:
            size: root.clamped_width * 0.37, root.height
            pos: root.center_x - (root.clamped_width * 0.3) / 2, root.y
            radius: [dp(25), ]

        Color: 
            rgba: 1, 1, 1, 1
        RoundedRectangle:
            id: rect
            size: root.clamped_width * 0.34, root.height
            pos: root.center_x - (root.clamped_width * 0.39) / 2 , root.y
            radius: [dp(25), ]

        Color: 
            rgba: 120/255, 200/255, 214/255, 1
        RoundedRectangle:
            size: root.clamped_width * 0.4, root.height
            pos: root.center_x - (root.clamped_width * 0.51) / 2 , root.y
            radius: [dp(25), ]  

    BoxLayout:
        id: selected_box
        size_hint: None, None
        height: dp(32)
        width: min(root.clamped_width * 0.5, dp(400))   # clamp width of the preview box
        x: root.center_x - self.width / 2
        y: root.y + root.height + dp(8)   # place above the bar with small gap
        padding: dp(8), 0
        spacing: dp(8)
        opacity: 1 if root.selected_image_name else 0
        canvas.before:
            Color:
                rgba: 0.95, 0.95, 0.95, 1
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [dp(10),]
        Label:
            id: selected_label
            text: root.selected_image_name if root.selected_image_name else ""
            text_size: (self.width, None)
            size_hint_x: 1
            valign: "middle"
            halign: "left"
            color: 0, 0, 0, 1
            shorten: True
            shorten_from: "right"
        Button:
            size_hint: None, None
            size: dp(28), dp(28)
            text: "x"
            color: (0,0,0,1)
            background_normal: ""
            background_color: 0, 0, 0, 0
            on_release: root.clear_selection()

    TextInput:
        id: message_input
        multiline: False
        hint_text: "Type a message..."
        font_size: 20
        width: root.clamped_width * 0.4
        height: root.height
        x: root.center_x - (self.width * 1.26) / 2
        y: root.y
        background_normal: ""
        background_active: ""
        background_color: 1, 0, 0, 0
        foreground_color: 0, 0, 0, 1
        padding: [dp(10), dp(20), dp(10), dp(10)]

    Button:
        text: ""
        background_color: 0, 0, 0, 0
        size_hint: None, None
        width: dp(48)
        height: root.height
        x: message_input.right + dp(4)
        y: root.y
        on_press: root.on_send_pressed()

    Button:
        text: ""
        background_color: 0, 1, 0, 0
        size_hint: None, None
        width: dp(48)
        height: root.height * 0.4
        x: message_input.right - root.clamped_width * 0.4
        y: root.y
        on_press: root.open_file_chooser()

    Label:
        font_name: "FA"
        size_hint: None, None
        width: dp(48)
        height: root.height
        x: message_input.right + 10
        y: root.y
        text: u"\uf139"
        font_size: dp(30)
        color: 1, 1, 1, 1

    Label:
        font_name: "FA"
        size_hint: None, None
        width: dp(48)
        height: root.height * 0.4
        x: message_input.right - root.clamped_width * 0.4 - 2
        y: root.y + 6
        text: u"\uf055 "
        font_size: dp(20)
        color: 0, 0, 0, 1

<HomeScreen>:
    FloatLayout:
        Label:
            id: doctor_title
            text: "DoctorAI"
            font_size: dp(50)
            bold: True
            opacity: 0.2
            pos_hint: {"center_x": 0.5, "center_y" : 0.65}
            y: Window.height*0.2

        ScrollView:
            id: scroll_box
            size_hint: None, None
            width: root.width * 0.6
            height: root.height * 0.6
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            do_scroll_x: False
            do_scroll_y: True

            GridLayout:
                id: messages_box
                cols: 1
                size_hint_y: None
                size_hint_x: None         # allow the grid to control its own width
                width: self.parent.width  # make it match the ScrollView width
                height: self.minimum_height
                padding: dp(10)
                spacing: dp(10)


        TextBar:
            id: textbar
            message_sent: root.on_message_sent   
            size_hint: None, None
            width: root.width
            height: dp(80)
            x: (root.width - self.width) / 2
            y: (root.height - self.height) / 2
        
